### ISSUE TITLE
您好，请问coco数据集各模型mAP指标分别是多少？

### ISSUE THREAD

**Issue by dsp6414** [wuzhihao7788/yolodet-pytorch#1]
你的代码结构很好，如果有mAP性能分析就更好了

**Comment by wuzhihao7788** [comment]
在MODEL_ZOO_cn.md文件里有详细说明。
![image](https://user-images.githubusercontent.com/49713405/97792760-9850e600-1c1d-11eb-95e8-8f9c67e16aae.png)
![image](https://user-images.githubusercontent.com/49713405/97792771-bae2ff00-1c1d-11eb-8488-86e798f17319.png)

**Comment by wuzhihao7788** [comment]
> 你的代码结构很好，如果有mAP性能分析就更好了

信息的统计指标在这个位置 https://github.com/wuzhihao7788/yolodet-pytorch/tree/master/docs/logs
由于我的条件非常有限，没有充分的训练模型。给出的模型都是只训练了24个epoch的模型。
![image](https://user-images.githubusercontent.com/49713405/97792813-60966e00-1c1e-11eb-82d6-53872a457471.png)
相关的统计模型指令在这里：
python tools/test.py --config 你配置问路径 --checkpoint 模型文件位置 --augment 是否启用TTA --coco-val-path coco验证集标签位置 --save-json

**Comment by deep-practice** [comment]
ppyolo效果比yolov5还好这么多？
