### ISSUE TITLE
能详细说明下数据集格式吗？

### ISSUE THREAD

**Issue by dsp6414** [wuzhihao7788/yolodet-pytorch#3]
期待您的回复

**Comment by dsp6414** [comment]
看代码好像是下面这种形式
图像绝对路径 x1,y1,x2,y2,cls ...
...

不晓得对不对

**Comment by dsp6414** [comment]
从train.txt加载，放到一个字典里。

**Comment by wuzhihao7788** [comment]
> 看代码好像是下面这种形式
> 图像绝对路径 x1,y1,x2,y2,cls ...
> ...
> 
> 不晓得对不对

![image](https://user-images.githubusercontent.com/49713405/97792798-25943a80-1c1e-11eb-975f-6be5f8e6fb1b.png)

**Comment by wuzhihao7788** [comment]
> > 看代码好像是下面这种形式
> > 图像绝对路径 x1,y1,x2,y2,cls ...
> > ...
> > 不晓得对不对
> 
> ![image](https://user-images.githubusercontent.com/49713405/97792798-25943a80-1c1e-11eb-975f-6be5f8e6fb1b.png)
请查看这个链接
https://github.com/wuzhihao7788/yolodet-pytorch/blob/master/docs/INSTALL_cn.md

**Comment by dsp6414** [comment]
谢谢你的回复，明白了
