### ISSUE TITLE
请问如何设置不用mosaic训练？训练自己数据集可否不用修改anchor?

### ISSUE THREAD

**Issue by dsp6414** [wuzhihao7788/yolodet-pytorch#4]

**Comment by wuzhihao7788** [comment]
请问你打算采用哪个模型训练代码？
在cfg文件夹路径下
修改该部分内容,有三个管道可配置，train，val，test
![image](https://user-images.githubusercontent.com/49713405/98000919-fea95480-1e27-11eb-868d-420f98ca6e2a.png)
在yolodet/utils/registry.py文件中包含所有的支持方法
![image](https://user-images.githubusercontent.com/49713405/98001074-2e585c80-1e28-11eb-9944-751e8c11f31a.png)

**Comment by wuzhihao7788** [comment]
一般情况下可以不修改anchor的大小。如果训练充分的话，模型也能收敛的很好

**Comment by dsp6414** [comment]
我用的yolov4模型训练yymnist数据集，mAP一直提高不上去，一直在.38附近徘徊，batch_size为32, division参数设置成8,没有采用预训练

**Comment by wuzhihao7788** [comment]
> 我用的yolov4模型训练yymnist数据集，mAP一直提高不上去，一直在.38附近徘徊，batch_size为32, division参数设置成8,没有采用预训练
这样，你把你的微信发我邮箱，我们单独私聊 753993117@qq.com
